# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './UI/OpenDatabase.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenDatabase(object):
    def setupUi(self, OpenDatabase):
        OpenDatabase.setObjectName("OpenDatabase")
        OpenDatabase.resize(335, 206)
        OpenDatabase.setMinimumSize(QtCore.QSize(335, 206))
        OpenDatabase.setMaximumSize(QtCore.QSize(335, 206))
        self.label = QtWidgets.QLabel(OpenDatabase)
        self.label.setGeometry(QtCore.QRect(101, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(OpenDatabase)
        self.line.setGeometry(QtCore.QRect(-3, 50, 501, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit = QtWidgets.QLineEdit(OpenDatabase)
        self.lineEdit.setGeometry(QtCore.QRect(52, 108, 221, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(OpenDatabase)
        self.label_2.setGeometry(QtCore.QRect(10, 107, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(OpenDatabase)
        self.pushButton.setGeometry(QtCore.QRect(250, 170, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.toolButton = QtWidgets.QToolButton(OpenDatabase)
        self.toolButton.setGeometry(QtCore.QRect(285, 108, 31, 21))
        self.toolButton.setObjectName("toolButton")
        self.radioButton = QtWidgets.QRadioButton(OpenDatabase)
        self.radioButton.setGeometry(QtCore.QRect(10, 80, 82, 21))
        self.radioButton.setObjectName("radioButton")

        self.retranslateUi(OpenDatabase)
        QtCore.QMetaObject.connectSlotsByName(OpenDatabase)

    def retranslateUi(self, OpenDatabase):
        _translate = QtCore.QCoreApplication.translate
        OpenDatabase.setWindowTitle(_translate("OpenDatabase", "Open Database"))
        self.label.setText(_translate("OpenDatabase", "Open Database"))
        self.label_2.setText(_translate("OpenDatabase", "path:"))
        self.pushButton.setText(_translate("OpenDatabase", "Connect"))
        self.toolButton.setText(_translate("OpenDatabase", "..."))
        self.radioButton.setText(_translate("OpenDatabase", "Defualt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OpenDatabase = QtWidgets.QDialog()
    ui = Ui_OpenDatabase()
    ui.setupUi(OpenDatabase)
    OpenDatabase.show()
    sys.exit(app.exec_())
